version: "3.9"

services:
    #Container MYSQL
    db:
        image: mysql
        container_name: novi_docebo_db
        restart: always
        volumes:
            - db-data-novi-docebo:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_novi_docebo@2023
            MYSQL_DATABASE: db_novi_docebo
            MYSQL_USER: admin
            MYSQL_PASSWORD: root_novi_docebo@2023
        networks:
            - novi-docebo

    #APACHE + PHP 8.2.3 ON FOLDER PHP INSIDE FOLDER DOCKER
    www:
        build: docker/php
        container_name: novi_docebo_www
        ports:
            - 1010:80
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/
        restart: always
        networks:
            - novi-docebo
    
    #Container PHPMYADMIN
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        container_name: novi_docebo_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PHP_UPLOAD_MAX_FILESIZE: 1G
            PHP_MAX_INPUT_VARS: 1G
            UPLOAD_LIMIT: 1G
        ports:
            - "1011:80"
        networks:
            - novi-docebo

    #REDIS
    redis:
        image: redis:6.2.1-alpine
        container_name: novi_docebo_redis
        command: redis-server --requirepass redis_reporting@2023
        ports:
            - '1012:6379'
        networks:
            - novi-docebo
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: novi_docebo_rabbitmq
        ports:
            - 1013:5672
            - 1014:15672
        environment:
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit delivery_acknowledgments_timeout 3600000"
        networks:
            - novi-docebo 
             
networks:
    novi-docebo:

volumes:
    db-data-novi-docebo:
