<?php
return [
    '2' => 'PersonalEmail',
    '7' => 'JobTitle',
    '8' => 'Credentials',
    '13' => 'MemberProfile',
    '14' => 'Image',
    '15' => 'Education',
    '16' => 'Awards',
    '17' => '',
    '18' => 'Exam ',
    '21' => 'AAID District',
    '22' => 'AAID Member ID',
    '23' => 'ABOI year',
    '24' => 'AGD Number',
    '28' => 'MaxiCourse Location',
    '29' => 'MaxiCourse Participant Checkbox',
    '30' => 'MaxiCourse Year',
    '31' => 'Part 2 Exam Eligibility Deadline',
    '33' => 'Professional Role',
    '42' => 'MemberSince',
    '43' => 'MembershipExpires',
    '44' => 'Gender',
    '46' => 'MemberType',
    '47' => 'UniqueID',
    '49' => 'MemberStatus',
    '50' => 'OpenDuesBalance',
];
